name: 'Deploy Aws Elastic Beanstalk Action'
description: 'A GitHub Action that takes an input and returns the square of the number'
inputs:
  aws_access_key:
    description: 'AWS Access Key'
    required: true
  aws_secret_key:
    description: 'AWS Secret Key'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    - name: Create deployment package
      run: |
        echo '${{ secrets.AWS_ACCESS_KEY_ID }}'
        echo '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
      shell: bash
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        application_name: 'TODO_List'
        environment_name: 'TODOList-env'
        region: 'ap-southeast-1'
        deployment_package: 'deployment_package.zip'
