name: Deploy Aws Elastic Beanstalk Action Workflow
on:
  push:
    branches:
      - master

jobs:
  deploy-eb:
    runs-on: ubuntu-latest
    name: Deploy to AWS Elastic Beanstalk
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy AWS Eb Action
        id: deploy_eb
        uses: ./ # Uses an action in the root directory
        # or use a released GitHub Action
        # uses: shipyard/github-action/fetch-shipyard-env@1.0.0
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
